#!/bin/bash

set -x

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/idd/forecastModels.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/idd/forecastProdsAndAna.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/idd/obsData.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/idd/satellite.xml"


# RADARS
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/PTA/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/OHA/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NVW/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NVL/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NTP/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NST/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NMD/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NET/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NCR/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBX/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBU/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBQ/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBM/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBK/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBH/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NBC/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAX/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAU/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAQ/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAM/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAK/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAH/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/NAC/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3X/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3U/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3S/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3Q/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3M/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3K/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3H/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N3C/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2X/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2U/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2S/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2Q/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2M/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2K/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2H/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N2C/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1X/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1U/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1S/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1Q/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1P/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1M/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1K/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1H/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N1C/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0Z/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0X/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0V/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0U/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0S/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0R/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0Q/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0M/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0K/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0H/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0C/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/HHC/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/EET/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DVL/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DU6/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DU3/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DTA/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DSP/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DSD/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DPR/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DPA/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DOD/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DHR/catalog.xml"
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level3/DAA/catalog.xml"

### 
curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/terminal/level3/catalog.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/level2/catalog.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/nexrad/composite/gini/catalog.xml"

curl http://localhost:8002/index -X POST -d "catalog_url=http://thredds.ucar.edu/thredds/catalog/grib/nexrad/composite/unidata/catalog.xml"
